### ISSUE TITLE
Transformations

### ISSUE THREAD

**Issue by chriscarex** [xml3d/xml3d-stl-plugin#1]
Hi,
it would be great to add the possibility to apply CSS transformations to the STL.
From my trials, it should not work at the moment.
If there's a way to apply them now (v5.0.1) please let me know!
Christian

**Comment by ksons** [comment]
Hi,

the `<mesh>` element that references the STL file, or any parent `group` element is transformable, for instance using CSS. In the [example](http://xml3d.github.io/xml3d-stl-plugin/examples/), open a console and try:

```
document.querySelector("mesh").style.transform = "translate3d(2px, 1px, -3px)"
```

Works for me.

**Comment by chriscarex** [comment]
perfect it works
