### ISSUE TITLE
Bounding Box

### ISSUE THREAD

**Issue by chriscarex** [xml3d/xml3d-stl-plugin#2]
Hi,
wanted to know if bounding box is supported for stl files uploaded with this plug-in and how can I get the values, or otherwise I recommend to add this feature to the plugin.
Thanks,
Christian

**Comment by ksons** [comment]
The `<mesh>` element referencing the STL file has a method `getLocalBoundingBox` which returns the object space bounding box of the STL file.  In the [example](http://xml3d.github.io/xml3d-stl-plugin/examples/), open a console and try:

```
document.querySelector("mesh").getLocalBoundingBox().toString()
```

Works for me.

**Comment by chriscarex** [comment]
this works as well, thanks
